# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  host: <%= Rails.application.credentials.pg.host %>
  database: <%= Rails.application.credentials.pg.database %>
  username: <%= Rails.application.credentials.pg.username %>
  password: <%= Rails.application.credentials.pg.password %>

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

production:
  <<: *default

development:
  # <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ratemyskipper_development
  # These could be set explicitly to avoid needing encrypted files for development, but this feels the cleanest
  # host: <%= Rails.application.credentials.pg.host %>
  # database: <%= Rails.application.credentials.pg.database %>
  # username: <%= Rails.application.credentials.pg.username %>
  # password: <%= Rails.application.credentials.pg.password %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: ratemyskipper_test
#   pool: 5
#   username: ratemyskipper
#   password: ratemyskipper
#   timeout: 5000

test:
  <<: *default
